import type { Metadata, Viewport } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import { cn } from "@/lib/utils"

import "./globals.css";

import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import { SiteHeader } from "@/components/site-header";
import { Toaster } from "@/components/ui/toaster";
// import { NextAuthProvider } from "@/components/nextAuthProvider";
import Sidebar from '@/components/sidebar'

export const metadata: Metadata = {
  title: "Nurcahyo App",
  description: "Generated by create next app",
  keywords: ["nextjs", "react", "typescript"],
  authors: [{
    name: "nurcahyo",
    url: "https://www.nurcahyo.com",
  }],
};
export const viewport: Viewport = {
  colorScheme: "dark light",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
}
interface RootLayoutProps { children: React.ReactNode }

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning className="bg-background">
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          GeistSans.variable,
          GeistMono.variable
        )}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>

          <div className='relative h-full overflow-hidden bg-background'>
      

            {/* <NextAuthProvider> */}
              <div className="flex-1">{children}</div>
              <Toaster />
            {/* </NextAuthProvider> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
